services:
  # --- Servizi di Infrastruttura (Zookeeper, Kafka, etcd rimangono invariati) ---

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "cub", "zk-ready", "zookeeper:2181", "60"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "cub", "kafka-ready", "-b", "kafka:29092", "1", "60"]
      interval: 10s
      timeout: 5s
      retries: 5

  etcd:
    image: bitnami/etcd:3.5
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- CORREZIONE: Definizione dei 3 Nodi per il Redis Cluster ---

  redis-node-1:
    image: redis:7-alpine
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "7000:6379" # Porta esterna 7000

  redis-node-2:
    image: redis:7-alpine
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "7001:6379" # Porta esterna 7001

  redis-node-3:
    image: redis:7-alpine
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "7002:6379" # Porta esterna 7002

  # --- Istanze del Tuo Microservizio Cucina ---
  # Nota: Ora dipendono dai 3 nodi redis, non da un singolo servizio 'redis'
  kitchen-service-1:
    build: .
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
      etcd:
        condition: service_healthy
      # Dipende da tutti i nodi Redis
      redis-node-1:
        condition: service_started
      redis-node-2:
        condition: service_started
      redis-node-3:
        condition: service_started
    environment:
      - KITCHEN_ID=11111111-1111-1111-1111-111111111111
    ports:
      - "8001:8000"

  kitchen-service-2:
    build: .
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
      etcd:
        condition: service_healthy
      redis-node-1:
        condition: service_started
      redis-node-2:
        condition: service_started
      redis-node-3:
        condition: service_started
    environment:
      - KITCHEN_ID=22222222-2222-2222-2222-222222222222
    ports:
      - "8002:8000"

  kitchen-service-3:
    build: .
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
      etcd:
        condition: service_healthy
      redis-node-1:
        condition: service_started
      redis-node-2:
        condition: service_started
      redis-node-3:
        condition: service_started
    environment:
      - KITCHEN_ID=33333333-3333-3333-3333-333333333333
    ports:
      - "8003:8000"