version: "3.9"

services:
  # ================= FastAPI App =================
  menu_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menu_service
    command: uvicorn main:app --host 0.0.0.0 --port 9999 --reload
    ports:
      - "9999:9999"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=menu_service_group
      - ROUTING_SERVICE_URL=http://localhost:7777
      - DATABASE_URL=postgresql+psycopg2://postgres:example@postgres:5432/menu_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=menu_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  # ================= PostgreSQL =================
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=menu_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# ================= Volumes =================
volumes:
  postgres_data:

# ================= Network =================
networks:
  app-network:
    external: true
