version: "3.9"

services:
  # ================= FastAPI App =================
  menu_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menu_service
    command: uvicorn menu_service.main:app --host 0.0.0.0 --port 9999 --reload
    ports:
      - "9999:9999"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=menu_db
    depends_on:
      - kafka
      - mysql
    networks:
      - app-network

  # ================= Zookeeper =================
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka:
    image: 'bitnami/kafka:3.5.1'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./Kafka:/bitnami/kafka
    networks:
      - app-network
    depends_on:
      - zookeeper

  # ================= MySQL =================
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: menu_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

# ================= Network =================
networks:
  app-network:
    driver: bridge
