services:
  routing-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: routing-service
    environment:
      - PORT=8080
      - KAFKA_BOOTSTRAP=kafka:29092
      - MENU_SERVICE_URL=http://menu-service:8081
      - WINDOW_MS=15000
      - TOPIC_DISPONIBILITA=disponibilita
      - TOPIC_CONFERMA=conferma_ordine
      - TOPIC_STATUS=status
      - TOPIC_ORDERSTATUS=orderstatus
    ports:
      - "7777:7777"
    networks:
      - app-network


networks:
  app-network:
    external: true
