events {}

http {
    upstream routing_backend {
        server routing-service-1:8080;
        server routing-service-2:8080;
    }

    server {
        listen 7777;

        location / {
            proxy_pass http://routing_backend;

            # headers utili
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
